add p3-1
yurii9999/hw pull request #42
Opened 2018-03-05 19:43 UTC by yurii9999

2018-03-13 13:36 UTC, jzuken requested changes

2018-03-13 13:36 UTC, jzuken commented on sem2/hw3/p3-1/src/main/java/com/group144/kuzmin/HashTable.java
> +    public void delete(String key) throws NotFoundExcaption{
пробела не хватает перед скобкой

2018-03-13 13:36 UTC, jzuken commented on sem2/hw3/p3-1/src/main/java/com/group144/kuzmin/HashTable.java
> +public class HashTable {
а где javadoc?

2018-03-13 13:36 UTC, jzuken commented on sem2/hw3/p3-1/src/main/java/com/group144/kuzmin/HashTable.java
> +            throw new NotFoundExcaption();
а в чём смысл ловить исключение, чтобы потом бросить ровно то же самое?

2018-03-13 13:36 UTC, jzuken commented on sem2/hw3/p3-1/src/main/java/com/group144/kuzmin/HashTable.java
> +            throw e;
и вот этого я не понимаю, зачем тут его ловить?

2018-03-13 13:36 UTC, jzuken commented on sem2/hw3/p3-1/src/main/java/com/group144/kuzmin/List.java
> +            head = new ListElement(value, head);
параметр-тип генерика забыл

2018-03-13 13:36 UTC, jzuken commented on sem2/hw3/p3-1/src/main/java/com/group144/kuzmin/List.java
> +        temp.next = new ListElement(value, temp.next);
и тут

2018-03-13 13:36 UTC, jzuken commented on sem2/hw3/p3-1/src/main/java/com/group144/kuzmin/List.java
> +    protected class ListElement<T> {
для непубличных классов необязательно писать параметр-тип тут, он наследуется от объемлющего класса

2018-03-13 13:36 UTC, jzuken commented on sem2/hw3/p3-1/src/main/java/com/group144/kuzmin/HashTableList.java
> +class NotFoundExcaption extends Exception {
Exception
и лучше его описать в отдельном файле

2018-03-13 13:36 UTC, jzuken commented on sem2/hw3/p3-1/src/test/java/com/group144/kuzmin/HashTableTest.java
> +        } catch (NotFoundExcaption notFoundExcaption) {
в тестах не принято ловить исключения, лучше использовать атрибут expected аннотации Test

2018-03-13 13:36 UTC, jzuken commented on sem2/hw3/p3-1/src/test/java/com/group144/kuzmin/HashTableTest.java
> +public class HashTableTest {
а что так хило с тестами? тут можно много всего проверить

2018-03-25 13:59 UTC, yurii9999 commented on sem2/hw3/p3-1/src/main/java/com/group144/kuzmin/List.java
> +            head = new ListElement(value, head);
это ведь уже не актуально? после удаления типа у листЕлемента

2018-05-05 13:56 UTC, jzuken requested changes

2018-05-05 13:56 UTC, jzuken commented on sem2/hw3/p3-1/src/main/java/com/group144/kuzmin/List.java
> +     * @return
не нужен он тут

2018-05-05 13:56 UTC, jzuken commented on sem2/hw3/p3-1/src/main/java/com/group144/kuzmin/List.java
> +        StringBuffer result = new StringBuffer("[" + head.value.toString());
лучше использовать StringBuilder

2018-05-05 13:56 UTC, jzuken commented on sem2/hw3/p3-1/src/test/java/com/group144/kuzmin/HashTableTest.java
> +public class HashTableTest {
всё ещё мало тестов. коллизии надо проверить и т.п.

2018-06-04 14:27 UTC, merged