P2 2
yurii9999/hw pull request #44
Opened 2018-03-06 04:25 UTC by yurii9999

2018-03-13 13:43 UTC, jzuken requested changes

2018-03-13 13:43 UTC, jzuken commented on sem2/hw2/p2-2/src/main/java/com/group144/kuzmin/ConsolePrinter.java
> +    public void printArray(int[][] array) {
а можно как-то сделать так, чтобы не дублировать два раза один и тот же код обхода по спирали?

2018-03-13 13:43 UTC, jzuken commented on sem2/hw2/p2-2/src/main/java/com/group144/kuzmin/Main.java
> +            printer = new FilePrinter();
отступ потерялся

2018-03-13 13:43 UTC, jzuken commented on sem2/hw2/p2-2/src/test/java/com/group144/kuzmin/FilePrinterTest.java
> +        catch (IOException ex) {
опять же исключения в тестах обычно не ловят. произойдёт исключение, тест сам упадёт

2018-03-18 14:24 UTC, yurii9999 commented on sem2/hw2/p2-2/src/test/java/com/group144/kuzmin/FilePrinterTest.java
> +        catch (IOException ex) {
иде подчеркивает красным без трай - кэч

2018-03-18 14:52 UTC, yurii9999 commented on sem2/hw2/p2-2/src/test/java/com/group144/kuzmin/FilePrinterTest.java
> +        catch (IOException ex) {
просто throws в тестах дописать будет достаточно?

2018-03-19 04:00 UTC, jzuken commented on sem2/hw2/p2-2/src/test/java/com/group144/kuzmin/FilePrinterTest.java
> +        catch (IOException ex) {
прописывай throws Exception в методе теста

2018-04-15 13:58 UTC, merged