add p4-1
yurii9999/hw pull request #45
Opened 2018-03-12 18:06 UTC by yurii9999

2018-03-24 06:46 UTC, jzuken requested changes

2018-03-24 06:46 UTC, jzuken commented on sem2/hw4/p4-1/src/main/java/com/group144/kuzmin/List.java
> +        private ListElement next;
параметр-тип потерялся. и тут ещё ряд мест похожих есть

2018-03-24 06:46 UTC, jzuken commented on sem2/hw4/p4-1/src/main/java/com/group144/kuzmin/UniqueList.java
> +class AlreadyIncludedException extends RuntimeException { }
зачем оно непроверяемое?

2018-03-25 15:30 UTC, yurii9999 commented on sem2/hw4/p4-1/src/main/java/com/group144/kuzmin/UniqueList.java
> +class AlreadyIncludedException extends RuntimeException { }
наследник класса ведь не может кидать исключения которых не кидает его предок?

2018-05-05 11:56 UTC, jzuken commented
ээ, а зачем ты везде параметры-типы поудалял? я вроде бы ровно наоборот просил

2018-05-05 12:22 UTC, yurii9999 commented
я не очень понимаю тогда, зачем нужен отдельный параметр тип в приватных подклассах?

2018-05-05 18:37 UTC, jzuken commented
а, да, всё хорошо теперь. туплю

2018-05-25 12:42 UTC, merged